import card1 from "../assets/images/redcard.png";
import card2 from "../assets/images/yellowcard.png";
import card3 from "../assets/images/marooncard.png";
import card4 from "../assets/images/whitecard.png";
import card5 from "../assets/images/browncard.png";
import card6 from "../assets/images/ganeshcard.jpg";

export const SimpleCardsData = [
  {
    id: 101,
    title: "Red Invite Card with Bride And Groom Names",
    price: 10.25,
    sku: "AFF001",
    src: card1,
    gallery: [card1, card2,card3,card4 ],
    description: "This satin red card is elegant and personalized with bride and groom names.",
    comments: "Discounts apply on bulk orders.",
    height: "20",
    width: "14",
    weight: "90",
    variants: [card4],
  },
  {
    id: 102,
    title: "Simple Red and Yellow Card Invite",
    price: 5.0,
    sku: "AFF002",
    src: card2,
   gallery: [card1, card2,card3,card4 ],
    description: "A simple yet bright invitation in red and yellow tones.",
    comments: "Budget-friendly wedding card for every event.",
    height: "18",
    width: "13",
    weight: "85",
    variants: [card3],
  },
  {
    id: 103,
    title: "Red Vertical Personal Invite",
    price: 7.0,
    sku: "AFF003",
    src: card3,
    gallery: [card1, card2,card3,card4 ],
    description: "Vertical card with classic red design, customizable details.",
    comments: "Perfect for traditional Hindu weddings.",
    height: "22",
    width: "14",
    weight: "95",
    variants: [card3],
  },
  {
    id: 104,
    title: "Elegant Cream Card with Designer Pattern",
    price: 8.5,
    sku: "AFF004",
    src: card4,
    gallery: [card1, card2,card3,card4 ],
    description: "Elegant cream wedding card with intricate designer motifs.",
    comments: "Delivers a premium look at an affordable price.",
    height: "21",
    width: "15",
    weight: "100",
    variants: [card3],
  },
  {
    id: 105,
    title: "Classic Royal Blue Wedding Invite",
    price: 9.99,
    sku: "AFF005",
    src: card5,
    gallery: [card1, card2,card3,card5 ],
    description: "Royal blue foil print card perfect for regal ceremonies.",
    comments: "Shines best in natural light.",
    height: "23",
    width: "16",
    weight: "105",
    variants: [card3],
  },
  {
    id: 106,
    title: "Golden Border Traditional Invite Card",
    price: 6.75,
    sku: "AFF006",
    src: card6,
   gallery: [card1, card2,card3,card6 ],
    description: "Minimalist gold bordered card with traditional feel.",
    comments: "Great for simple yet elegant functions.",
    height: "19",
    width: "13",
    weight: "88",
    variants: [card3],
  },
];